cachegrand:
  cachegrand:
    image:
      repository: cachegrand/cachegrand-server
      tag: latest
  replicas: 1
  volumeClaims:
    backup:
      requests:
        storage: 10Gi
tls:
  enabled: false