apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-cachegrand-headless-svc
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app: cachegrand
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    name: non-ssl
{{- if .Values.tls.enabled }}    
  - port: 6380
    protocol: TCP
    targetPort: 6380
    name: ssl
{{- end }}     
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: prometheus
  type: ClusterIP